# Generated by Django 5.2.5 on 2025-09-19 10:46

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], max_length=100)),
                ('phone_number', models.CharField(default='+996', max_length=11)),
                ('expirience', models.CharField(max_length=300)),
                ('vacancy', models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend'), ('SMM', 'SMM')], max_length=100)),
                ('info_about_you', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'пользователя',
                'verbose_name_plural': 'пользователи',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
