# Generated by Django 5.2.5 on 2025-09-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='укажите название книги')),
                ('genre_book', models.CharField(choices=[('роман', 'роман'), ('рассказ', 'рассказ'), ('лирика', 'лирика')], default='рассказ', max_length=100)),
                ('images', models.ImageField(upload_to='books/', verbose_name='загрузите фото книги')),
                ('link_book', models.URLField(verbose_name='вставьте ссылку на оригинал книги')),
                ('description', models.TextField(verbose_name='описание книги')),
                ('author', models.TextField(max_length=50, verbose_name='укажите автора книги')),
                ('author_img', models.ImageField(upload_to='books/', verbose_name='загрузите фото')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='укажите ссылку с youtube')),
                ('comment', models.TextField(verbose_name='оставьте мнение читателей о книге')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
    ]
