# Generated by Django 5.2.5 on 2025-09-09 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='как вас зовут ?')),
                ('surname', models.CharField(max_length=15, verbose_name='Ваша фамилия ?')),
            ],
            options={
                'verbose_name': 'Турист',
                'verbose_name_plural': 'Туриста',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, verbose_name='Введите дату тура')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tourist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tourist', to='tours.tourist')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
