# Generated by Django 5.2.5 on 2025-09-23 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='фильм1', max_length=100)),
                ('description', models.TextField(default='Описание фильма')),
                ('genre', models.CharField(choices=[('Фантастика', 'Фантастика'), ('Хорор', 'Хоррор')], default='Фантастика', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Романтика', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=100, null=True)),
                ('choice_films', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='cineboard.films')),
            ],
        ),
        migrations.AddField(
            model_name='films',
            name='tags',
            field=models.ManyToManyField(to='cineboard.tag'),
        ),
    ]
