# Generated by Django 5.2.5 on 2025-09-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='genre',
            field=models.CharField(choices=[('Романтика', 'Романтика'), ('Хоррор', 'Хоррор')], default='Фантастика', max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='фантастика', max_length=100),
        ),
    ]
