# Generated by Django 5.2.5 on 2025-09-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineboard', '0002_alter_films_genre_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
