# Generated by Django 5.2.5 on 2025-09-14 10:10

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Введите имя')),
                ('surname', models.CharField(max_length=15, verbose_name='Введите фамилию')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KG', unique=True)),
                ('card_number', models.CharField(max_length=16, verbose_name='Введите номер карты')),
                ('choice_type', models.CharField(choices=[('Выполнено', 'Выполнено'), ('Не выполнено', 'Не выполнено')], max_length=100, verbose_name='выберите статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
